name: Deploy Next.js SSG to cPanel via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build Next.js front-office
        working-directory: ./front-office
        run: |
          npm install
          npm run build

      - name: Deploy Next.js build via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.magservices-mali.org
          username: c2285360c
          password: CRPFNC6ws67sF7x
          protocol: ftps
          local-dir: ./front-office/
          server-dir: /public_html/website/
